---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    versioning-strategy: "auto"
    assignees:
      - "Bryvn01"
    reviewers:
      - "Bryvn01"
    groups:
      production-deps:
        dependency-type: "production"
        patterns:
          - "*"
      development-deps:
        dependency-type: "development"
        patterns:
          - "*"
    ignore:
      - dependency-name: "Django"
        versions:
          - ">=6"
