#!/bin/bash

echo "🚀 EasyCart - Deployed on Render"

echo "✅ Application is live on Render!"
echo ""
echo "🌐 Frontend Application:"
echo "   https://easycart-frontend-zge5.onrender.com"
echo ""
echo "⚙️  Backend API:"
echo "   https://easycart-backend-0u8r.onrender.com"
echo ""
echo "👨‍💼 Admin Dashboard:"
echo "   https://easycart-admin.onrender.com"
echo ""
echo "🧪 Test Admin Login:"
echo "   Email: admin@easycart.com"
echo "   Password: admin123"
echo "   URL: https://easycart-admin.onrender.com/admin/login"
echo ""
echo "📊 Seed Database:"
echo "   curl -X POST https://easycart-backend-0u8r.onrender.com/api/seed"
echo ""
echo "📖 Deployment Guide: See RENDER_DEPLOY.md for setup instructions"