# Generated by Django 5.1.5 on 2025-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('mpesa',
                     'M-Pesa'),
                    ('airtel',
                     'Airtel Money'),
                    ('tkash',
                     'T-Kash'),
                    ('card',
                     'Credit/Debit Card'),
                    ('bank',
                     'Bank Transfer'),
                    ('cash',
                     'Cash on Delivery')],
                default='mpesa',
                max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Pending'),
                    ('processing',
                     'Processing'),
                    ('completed',
                     'Completed'),
                    ('failed',
                     'Failed'),
                    ('cancelled',
                     'Cancelled')],
                db_index=True,
                default='pending',
                max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(
                default='0700000000',
                max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Pending'),
                    ('processing',
                     'Processing'),
                    ('shipped',
                     'Shipped'),
                    ('delivered',
                     'Delivered'),
                    ('cancelled',
                     'Cancelled')],
                db_index=True,
                default='pending',
                max_length=20),
        ),
    ]
