# Generated by Django 5.2.7 on 2025-11-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_stripe_paypal_payment_methods"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
