# Generated by Django 4.2.30 on 2026-04-10 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='orders_orde_recipie_cf5101_idx'), models.Index(fields=['is_read'], name='orders_orde_is_read_86137e_idx'), models.Index(fields=['order', 'order_status'], name='orders_orde_order_i_a028e0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ordernotification',
            constraint=models.UniqueConstraint(fields=('order', 'recipient', 'order_status'), name='unique_order_notification_per_status_recipient'),
        ),
    ]
