# Generated by Django 5.1.7 on 2025-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_historicaluser_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="otp_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="otp_last_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_last_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
