# Generated by Django 5.2.7 on 2025-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_otpdeliverylog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otpdeliverylog",
            new_name="accounts_ot_created_c25935_idx",
            old_name="accounts_ot_created_idx",
        ),
        migrations.RenameIndex(
            model_name="otpdeliverylog",
            new_name="accounts_ot_deliver_7fe1e1_idx",
            old_name="accounts_ot_deliver_idx",
        ),
        migrations.RenameIndex(
            model_name="otpdeliverylog",
            new_name="accounts_ot_success_bdd5af_idx",
            old_name="accounts_ot_success_idx",
        ),
    ]
