# Generated by Django 5.1.14 on 2025-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="preferred_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="User-chosen display username (optional, must be unique)",
                max_length=30,
                null=True,
                verbose_name="Preferred Username",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_username",
            field=models.CharField(
                blank=True,
                help_text="User-chosen display username (optional, must be unique)",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Preferred Username",
            ),
        ),
    ]
