# Generated by Django 5.1.14 on 2025-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_historicaluser_preferred_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the verification email was last sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has verified their email address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the verification email was last sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has verified their email address",
            ),
        ),
    ]
