# Generated by Django 5.2.7 on 2025-12-15 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("page_url", models.URLField(blank=True, max_length=500)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("agent", "Support Agent"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender_id", models.IntegerField(blank=True, null=True)),
                ("message_text", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="supportconversation",
            index=models.Index(
                fields=["user", "-created_at"], name="support_sup_user_id_4725f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportconversation",
            index=models.Index(
                fields=["status", "-created_at"], name="support_sup_status_66b5e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportconversation",
            index=models.Index(
                fields=["user_email", "-created_at"],
                name="support_sup_user_em_ffe708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="support_sup_convers_23198a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["sender_type", "is_read"], name="support_sup_sender__e7a79c_idx"
            ),
        ),
    ]
