# Generated by Django 3.2.25 on 2025-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_historicalcategory_historicalproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/gallery/"),
        ),
    ]
