# Generated by Django 5.2.7 on 2025-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20251022_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
