# Generated by Django 5.2.7 on 2025-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_add_category_image_url"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-view_count"], name="products_pr_view_co_cba56c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
        ),
    ]
