# Generated by Django 5.2.7 on 2025-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='blurhash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='blurhash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
